#!/bin/bash

rm /tmp/.X0-lock && mv /var/log/*.log /root/logs/

x0vncserver -display $DISPLAY -passwordfile /root/.vnc/passwd &
/usr/share/novnc/utils/launch.sh --vnc localhost:5900&
service xrdp start && xrdp &

ulimit -s unlimited
nvidia-smi

startxfce4 &

export DISPLAY=:0&&xterm -e "xset s off" &
export DISPLAY=:0&&xterm -e "neofetch && tail -f /dev/null" &
export DISPLAY=:0&&exo-open --launch TerminalEmulator &

cd /Bonsai/runtime && ./bonsai2_slowdust -t 0.00001 --displayfps -T 1000 -i model3_child_compact.tipsy

tail -f /dev/null
