FROM twobombs/thereminq-bonsai

# add and convert validation csv data
RUN tar -xf /thereminq-bonsai/miscfiles/validation_method_comparison_all.tar.gz -C /thereminq-bonsai/buildscripts/
RUN cd /thereminq-bonsai/buildscripts/validation_method_comparison_all && chmod 744 ../import_csv.sh &&  cp ../import_csv.sh import_csv.sh && ./import_csv.sh 

EXPOSE 22 6080 8801-8811
ENTRYPOINT /root/run-bonsai-validate
