FROM twobombs/cudacluster:vulkan

# install features
RUN apt-get update && apt-get -y install build-essential cmake openssh-server wget vim-common opencl-headers curl libfreetype6-dev autotools-dev libicu-dev libbz2-dev libboost-all-dev && apt-get clean all

# fetch scripts and data repos
RUN git clone --depth=1 https://github.com/twobombs/thereminq.git && cd /thereminq/buildscripts && chmod 744 * 
RUN git clone --depth=1 https://github.com/twobombs/thereminq-bonsai.git && cd /thereminq-bonsai/buildscripts && chmod 744 *

# fetch firefly [test]
RUN git clone --depth=1 https://github.com/ageller/Firefly.git && cd Firefly && pip3 install -e .

# install bonsai
RUN apt update && export DEBIAN_FRONTEND=noninteractive && apt install -y git cmake-curses-gui && apt clean all
RUN apt-get update && apt-get -y install time build-essential cmake openssh-server wget vim-common opencl-headers curl libfreetype6-dev freeglut3-dev autotools-dev libicu-dev libbz2-dev libboost-all-dev && apt-get clean all

RUN git clone --depth=1 https://github.com/treecode/Bonsai.git
RUN cd /Bonsai/runtime/lib && mv linux linux_temp && mv linux_fpic_glew linux
RUN cd /Bonsai/runtime && cmake -DCMAKE_CXX_COMPILER=mpicxx -DUSE_CUB=0 -DUSE_OPENGL=1 -DCUDA_CUDART_LIBRARY=/usr/local/cuda/lib64/libcudart.so && make -i -k -j $(grep -c ^processor /proc/cpuinfo) && cd /Bonsai/tools/IO && make -i -k -j $(grep -c ^processor /proc/cpuinfo)

# install haskell, z3, num-utils, crackNum + dependancies
RUN apt-get install -y z3 num-utils && apt clean all
RUN curl -sSL https://get.haskellstack.org/ | sh
# RUN git clone --depth=1 https://github.com/LeventErkok/crackNum.git
RUN wget https://github.com/LeventErkok/crackNum/archive/refs/tags/v3.3.tar.gz && tar -xzvf v3.3.tar.gz && mv crackNum-3.3 crackNum
RUN cd crackNum && stack path --local-bin && stack setup && stack init && stack build && stack install && stack clean && rm -R /crackNum

# node run & benchmark script, make runnable 
COPY runscripts/run* /root/
RUN chmod 744 /root/run*

#cleanup
RUN mkdir /root/logs && mv /var/log/*.log /root/logs/

EXPOSE 22 80 8801-8811
ENTRYPOINT /root/run-bonsai
