FROM twobombs/thereminq-bonsai

# install bonsai
RUN apt update && export DEBIAN_FRONTEND=noninteractive && apt install -y git cmake-curses-gui && apt clean all
RUN apt-get update && apt-get -y install time build-essential cmake openssh-server wget vim-common opencl-headers curl libfreetype6-dev freeglut3-dev autotools-dev libicu-dev libbz2-dev libboost-all-dev && apt-get clean all

# add and convert demo data
RUN tar -xf /thereminq/miscfiles/qrack-cosmos.tar.gz -C /var/log/
RUN cd /thereminq/buildscripts && ./makeqftipsy.sh
RUN cat /proc/cpuinfo > /thereminq/cpuinfo.txt

EXPOSE 22 6080 8801-8811
ENTRYPOINT /root/run-bonsai-realtime
