FROM twobombs/thereminq-bonsai:qrack-precooked

# add clblast repo for 20.04
RUN add-apt-repository -y ppa:cnugteren/clblast

# fetch dependancies
RUN export DEBIAN_FRONTEND=noninteractive && apt update && apt install -y git python3-pip mc sudo wget libopenblas-dev libclblast-dev && apt clean all

#fetch llama.cpp
RUN git clone --depth=1 https://github.com/ggerganov/llama.cpp
RUN cp -r llama.cpp llama-openblas
RUN cp -r llama.cpp llama-cublas
RUN cp -r llama.cpp llama-clblast

# build all versions
RUN cd llama.cpp && make -j
RUN cd llama-openblas && cmake . && make LLAMA_OPENBLAS=1 all
RUN cd llama-cublas && cmake -DGGML_CUBLAS=ON . && make LLAMA_CUBLAS=1 all
RUN cd llama-clblast && cmake -DGGML_CLBLAST=ON . && make LLAMA_CLBLAST=1 all

# RUN wget https://huggingface.co/Twobombs/llama31-8B/resolve/main/Meta-Llama3.1-8B-q3_K.gguf
RUN touch Meta-Llama3.1-8B-q3_K.gguf

EXPOSE 22 6080 8801-8811
ENTRYPOINT /root/run-bonsai-graph
