FROM twobombs/thereminq-bonsai

# upgrade image because of nv not upgrading
RUN apt update && apt -y upgrade && apt clean all

# generate build-time CPU driven qcircuits with vector analysis
# RUN cd root && /usr/bin/time ./run-qcircuit

EXPOSE 22 80 8801-8811
ENTRYPOINT /root/run
