FROM twobombs/thereminq-bonsai

# add and convert demo data
RUN tar -xf /thereminq/miscfiles/qrack-cosmos.tar.gz -C /var/log/
RUN cd /thereminq/buildscripts && ./makeqftipsy.sh
RUN cat /proc/cpuinfo > /thereminq/cpuinfo.txt

EXPOSE 22 6080 8801-8811
ENTRYPOINT /root/run-bonsai-realtime
